backend:
  name: github
  repo: inesb18/monsite

media_folder: static/assets
public_folder: /assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/index.md"
        label: "Accueil"
        name: "accueil"
        fields:
          - {
              label: "Bloc",
              name: "bloc",
              widget: "object",
              fields:
                [
                  { label: "Nom", name: "nom", widget: "string" },
                  { label: "Passionnée de", name: "passionneeDe", widget: "string" },
                  { label: "Domaines", name: "domaines", widget: "list", field: { label: "Domaine", name: "domaine", widget: "string" } },
                ],
            }
          - {
              label: "Liens",
              name: "links",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Type de lien", name: "typeLien", widget: "select", options: ["interne", "externe"] },
                  { label: "URL", name: "URL", widget: "string", hint: "Utilisez un chemin relatif (ex /about) si le lien est interne." },
                ],
            }
          - {
              label: "Lien vers à props",
              name: "lienVersAPropos",
              widget: "object",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Type de lien", name: "typeLien", widget: "select", options: ["interne", "externe"] },
                  { label: "URL", name: "URL", widget: "string", hint: "Utilisez un chemin relatif (ex /about) si le lien est interne." },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Titre de l'onglet du navigateur", name: "titreOngletNav", widget: "string"},
                  { label: "Titre", name: "titre", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                  { label: "Keywords", name: "keywords", widget: "string" },
                ],
            }
      - file: "src/content/a-propos/index.md"
        label: "A propos"
        name: "aPropos"
        fields:
          - {
              label: "Photo",
              name: "photo",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Description courte de l'image (image alt)", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Texte", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Titre de l'onglet du navigateur", name: "titreOngletNav", widget: "string"},
                  { label: "Titre", name: "titre", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                  { label: "Keywords", name: "keywords", widget: "string" },
                ],
            }
      - file: "src/content/mentions-legales/index.md"
        label: "Mentions légales"
        name: "mentionsLegales"
        fields:
          - { label: "Texte", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Titre de l'onglet du navigateur", name: "titreOngletNav", widget: "string"},
                  { label: "Titre", name: "titre", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                  { label: "Keywords", name: "keywords", widget: "string" },
                ],
            }
      - file: "src/content/projets-tech/index.md"
        label: "Projets tech"
        name: "projetsTech"
        fields:
          - {
              label: "Projet",
              name: "projet",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Description courte de l'image (image alt)", name: "imageAlt", widget: "string" },
                  { label: "Nom", name: "nom", widget: "string" },
                  { label: "Description courte du projet", name: "description", widget: "string" },
                  { label: "URL", name: "URL", widget: string },
                  { label: "Roles", name: "roles", widget: "list", field: { label: "Role", name: "role", widget: "string"} },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Titre de l'onglet du navigateur", name: "titreOngletNav", widget: "string"},
                  { label: "Titre", name: "titre", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                  { label: "Keywords", name: "keywords", widget: "string" },
                ],
            }
  - name: "categoriePhoto"
    label: "Catégorie de photographie"
    folder: "src/content/photographie"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "photography" }
      - { label: "Ordre", name: "ordre", widget: "number" }
      - { label: "Titre", name: "titre", widget: "string" }
      - { label: "Photo de couverture", name: "photoCouverture", widget: "image" }
      - { label: "Photos", name: "photos", widget: list, field: {label: "Image", name: "image", widget: image} }
  - name: "navbarEtFooter"
    label: "Navbar & Footer"
    files:
      - file: "src/content/navbar/index.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
          - {
              label: "Items du menu",
              name: "itemsMenu",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Type de lien", name: "typeLien", widget: "select", options: ["interne", "externe"] },
                  { label: "URL", name: "URL", widget: "string", hint: "Utilisez un chemin relatif (ex /about) si le lien est interne." },
                ],
            }
      - file: "src/content/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - {
              label: "Droits et crédits",
              name: "droitsEtCredits",
              widget: "list",
              field: { label: "Une ligne", name: "uneLigne", widget: "string" }
            }
          - {
              label: "Links",
              name: "links",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Type de lien", name: "typeLien", widget: "select", options: ["interne", "externe"] },
                  { label: "URL", name: "URL", widget: "string", hint: "Utilisez un chemin relatif (ex /about) si le lien est interne." },
                ],
            }
