backend:
  name: github
  repo: inesb18/monsite

media_folder: static/assets
public_folder: /assets

media_library:
  name: cloudinary
  config:
    cloud_name: dfzwvorfrdfzwvorfr
    api_key: 753425461788875

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/index.md"
        label: "Accueil"
        name: "home"
        fields:
          - {
              label: "Bloc",
              name: "block",
              widget: "object",
              fields:
                [
                  { label: "Nom", name: "name", widget: "string" },
                  { label: "Passionnée de", name: "keenOn", widget: "string" },
                  { label: "Domaines", name: "fields", widget: "list", field: { label: "Domaine", name: "field", widget: "string" } },
                ],
            }
          - {
              label: "Liens",
              name: "links",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Type de lien", name: "linkType", widget: "select", options: ["interne", "externe"] },
                  { label: "URL", name: "URL", widget: "string", hint: "Utilisez un chemin relatif (ex /about) si le lien est interne." },
                ],
            }
          - {
              label: "Lien vers à props",
              name: "linkToAbout",
              widget: "object",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Type de lien", name: "linkType", widget: "select", options: ["interne", "externe"] },
                  { label: "URL", name: "URL", widget: "string", hint: "Utilisez un chemin relatif (ex /about) si le lien est interne." },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Titre de l'onglet du navigateur", name: "browserTitle", widget: "string"},
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                  { label: "Keywords", name: "keywords", widget: "string" },
                ],
            }
      - file: "src/content/a-propos/index.md"
        label: "A propos"
        name: "aPropos"
        fields:
          - {
              label: "Photo",
              name: "photo",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Description courte de l'image (image alt)", name: "imageAlt", widget: "string" },
                ],
            }
          - { label: "Texte", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Titre de l'onglet du navigateur", name: "browserTitle", widget: "string"},
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                  { label: "Keywords", name: "keywords", widget: "string" },
                ],
            }
      - file: "src/content/mentions-legales/index.md"
        label: "Mentions légales"
        name: "legalNotice"
        fields:
          - { label: "Texte", name: "body", widget: "markdown" }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Titre de l'onglet du navigateur", name: "browserTitle", widget: "string"},
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                  { label: "Keywords", name: "keywords", widget: "string" },
                ],
            }
      - file: "src/content/projets-tech/index.md"
        label: "Projets tech"
        name: "techProjects"
        fields:
          - {
              label: "Projets",
              name: "projects",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Description courte de l'image (image alt)", name: "imageAlt", widget: "string" },
                  { label: "Nom du projet", name: "name", widget: "string" },
                  { label: "Description courte du projet", name: "description", widget: "string" },
                  { label: "URL", name: "URL", widget: string },
                  { label: "Roles", name: "roles", widget: "list", field: { label: "Role", name: "role", widget: "string"} },
                ],
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  { label: "Titre de l'onglet du navigateur", name: "browserTitle", widget: "string"},
                  { label: "Titre", name: "title", widget: "string" },
                  { label: "Description", name: "description", widget: "string" },
                  { label: "Keywords", name: "keywords", widget: "string" },
                ],
            }
  - name: "photoCategories"
    label: "Catégories de photographie"
    folder: "src/content/photographie"
    create: true
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "photography" }
      - { label: "Ordre", name: "order", widget: "number" }
      - { label: "Titre de la catégorie", name: "title", widget: "string" }
      - { label: "Photo de couverture", name: "coverPicture", widget: "image" }
      - { label: "Photos", name: "photos", widget: list, field: {label: "Image", name: "image", widget: image} }
      - {
          label: "SEO & Meta",
          name: "seo",
          widget: "object",
          fields:
            [
              { label: "Titre de l'onglet du navigateur", name: "browserTitle", widget: "string"},
              { label: "Titre", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "string" },
              { label: "Keywords", name: "keywords", widget: "string" },
            ],
        }
  - name: "navbarEtFooter"
    label: "Navbar & Footer"
    files:
      - file: "src/content/navbar/index.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Logo", name: "logo", widget: "image" }
          - {
              label: "Items du menu",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Type de lien", name: "linkType", widget: "select", options: ["interne", "externe"] },
                  { label: "URL", name: "URL", widget: "string", hint: "Utilisez un chemin relatif (ex /about) si le lien est interne." },
                ],
            }
      - file: "src/content/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - {
              label: "Droits et crédits",
              name: "rightsAndCredits",
              widget: "list",
              field: { label: "Une ligne", name: "oneLine", widget: "string" }
            }
          - {
              label: "Links",
              name: "links",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Type de lien", name: "linkType", widget: "select", options: ["interne", "externe"] },
                  { label: "URL", name: "URL", widget: "string", hint: "Utilisez un chemin relatif (ex /about) si le lien est interne." },
                ],
            }
